---

- name: Install apache
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - apache2

- name: Install php5
  apt: name={{item}} state=installed
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-cli

- name: Install php extensions
  apt: name={{item}} state=installed
  with_items: php5_extensions

- name: Enable apache2 modules
  apache2_module: state=present name={{ item }}
  with_items:
    - expires
    - ssl
    - rewrite

- name: Push virtualhost configuration files
  template:
    src: "{{ item.template|default('vhost.symfony2.j2') }}"
    dest: "/etc/apache2/sites-enabled/{{ item.dest|default(item.name)}}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: sites
  when: sites is defined

- name: Remove default vhost in sites-enabled
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent

- name: Configure /etc/hosts
  lineinfile: dest=/etc/hosts line='127.0.0.1 {{ item.server_name }}' owner=root group=root mode=0644
  with_items: sites

- name: Configure php5-cli
  template: src=php.ini.j2 dest=/etc/php5/cli/php.ini owner=root group=root mode=0644

- name: Configure php5-apache
  template: src=php.ini.j2 dest=/etc/php5/apache2/php.ini owner=root group=root mode=0644

- name: Start apache2
  service: name=apache2 state=started
