---

- name: Add mongodb gpg key
  apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id=7F0CEB10 state=present

- name: Add mongodb repo
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present

- name: Install mongodb
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - mongodb-org
    - python-pip

- name: Install pymongo
  pip: name=pymongo state=present

- name: Configure mongodb without authentication
  template: src=mongod-noauth.conf.j2 dest=/etc/mongod.conf

- name: Start mongodb service without authentication
  service: name=mongod state=started

- name: Create mongodb users
  mongodb_user: >
    name={{ item.name }}
    password={{ item.password|default(item.name)}}
    database={{ item.database|default('admin') }}
    state=present
  with_items: '{{ mongodb.users|default([]) }}'

- name: Configure mongodb with authentication
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  when: mongodb.users is defined

- name: Restart mongodb service with authentication
  service: name=mongod state=restarted
  when: mongodb.users is defined
