---

- name: Add erlang gpg key
  apt_key: url=http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc state=present

- name: Add erlang repo
  apt_repository: repo='deb http://packages.erlang-solutions.com/ubuntu {{ ansible_lsb.codename }} contrib' state=present

- name: Install erlang
  apt: name=erlang state=present
