---
  - name: Add nodesource repo
    shell: curl -sL https://deb.nodesource.com/setup_5.x | bash -

  - name: Install node.js
    action: apt name=nodejs state=installed

  - name: Install npm packages
    npm: name={{item}} global=yes
    with_items:
      - npm
      - node-gyp
      - grunt-cli
      - gulp-cli
      - bower
      - pm2
      - mocha
