---

- name: Add nodesource repo
  shell: curl -sL https://deb.nodesource.com/setup_{{ node_version }} | bash -

- name: Install node.js
  apt: name=nodejs state=present

- name: Install npm global packages
  npm: name={{ item }} global=yes
  with_items: npm_packages
