---

- name: Add nginx ppa
  apt_repository: repo="ppa:nginx/stable" state=present

- name: Install nginx
  apt: name={{ nginx_package }} state=present

- name: Push virtualhost configuration files
  template: src={{ item.template|default('vhost.default.j2') }} dest=/etc/nginx/sites-enabled/{{ item.name }}.conf
  with_items: sites
  notify:
    - Restart nginx
