---

- name: Add ip/hostname couples to /etc/hosts file
  lineinfile:
    state: present
    dest: /etc/hosts
#    regexp: "^(?:[0-9]{1,3}{{ '.' | regex_escape() }}){3}[0-9]{1,3} {{ item.hostname | regex_escape() }}$"
    line: "{{ item.ip }} {{ item.hostname }}"
  with_items: '{{ etc_hosts_lines }}'
