- name: "Fetch Elasticsearch"
  action: get_url url={{ elasticsearch.url }}/{{ elasticsearch.deb.package }} dest={{ elasticsearch.tmp }} thirsty=yes mode=0440
  register: elasticsearch_deb

- name: "Install Elasticsearch package"
  action: shell dpkg -i -E --force-confnew {{ elasticsearch.tmp }}/{{ elasticsearch.deb.package }} 2>&1 | grep skipping | wc -l
  when: elasticsearch_deb.changed

- name: "Start Elasticsearch"
  sudo: yes
  service: name=elasticsearch state=started
