---

- name: Install apache2
  apt: name={{ item }} state=present
  with_items:
    - apache2

- name: Enable apache2 modules
  apache2_module: name={{ item }} state=present
  with_items:
    - expires
    - ssl
    - rewrite

- name: Push virtualhost configuration files
  template:
    src: "{{ item.template|default('vhost.default.j2') }}"
    dest: "/etc/apache2/sites-enabled/{{ item.dest|default(item.name)}}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: sites
  when: sites is defined

- name: Remove default vhost in sites-enabled
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent
  notify:
    - Restart apache2
