---

- name: Install apache2
  apt: name={{ item }} state=present
  with_items:
    - apache2

- name: Enable apache2 modules
  apache2_module: name={{ item }} state=present
  with_items:
    - expires
    - ssl
    - rewrite

- name: Push virtualhost configuration files
  template:
    src: "{{ item.template|default('vhost.default.j2') }}"
    dest: "/etc/apache2/sites-enabled/{{ item.name }}.conf"
  with_items: sites

- name: Remove default vhost in sites-enabled
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent
  notify:
    - Restart apache2
