---

- name: Install lua
  apt: name={{ item }} state=present
  with_items:
    - 'lua{{ lua_version }}'
    - luarocks

- name: Install lua packages
  apt: name={{ item }} state=present
  with_items: '{{ lua_packages }}'

- name: Install luarocks packages
  command: luarocks install {{ item }}
  with_items: '{{ luarocks_packages }}'
