---

- name: Add postgresql gpg key
  shell: wget -qO - https://postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

- name: Add postgresql repo
  apt_repository: repo="deb https://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main" state=present

- name: Install postgresql
  apt: name={{ item }} state=present
  with_items:
    - libpq-dev
    - 'postgresql-{{ postgresql_version }}'
    - postgresql-contrib
    - python-psycopg2

- name: Configure postgresql
  template: src={{ item }}.j2 dest=/etc/postgresql/{{ postgresql_version }}/main/{{ item }}
  with_items:
    - pg_hba.conf
    - postgresql.conf

- name: Start postgresql service
  service: name=postgresql state=restarted

- name: Create postgresql databases
  sudo: yes
  sudo_user: postgres
  postgresql_db: >
    name={{ item.name }}
    state=present
  with_items: postgresql.databases
  when: postgresql is defined and postgresql.databases is defined

- name: Create postgresql users
  sudo: yes
  sudo_user: postgres
  postgresql_user: >
    name={{ item.name }}
    password={{ item.password|default(item.name) }}
    role_attr_flags={{ item.role|default('SUPERUSER') }}
    state=present
  with_items: postgresql.users
  when: postgresql is defined and postgresql.users is defined
