---

- name: Add webupd8 repo
  apt_repository: repo=ppa:webupd8team/java state=present

- name: Select oracle license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections

- name: Install oracle java
  apt: name=oracle-java8-installer state=present
