---
- include: webupd8.yml

- name: Automatically select the Oracle License
  tags: java
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Install Oracle Java
  tags: java
  apt: pkg=oracle-java8-installer state=installed
