---

- name: Install packages required to build ruby (Debian).
  apt: "name={{ item }} state=present"
  with_items:
    - libcurl4-openssl-dev
    - libffi-dev
    - libgdbm-dev
    - libgdbm3
    - libncurses5-dev
    - libreadline-dev
    - libreadline6-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - zlib1g-dev

- name: Download ruby.
  get_url:
    url: "{{ ruby.download_url }}"
    dest: "/home/vagrant/ruby-{{ ruby.version }}.tar"

- name: Extract ruby.
  unarchive:
    src: "/home/vagrant/ruby-{{ ruby.version }}.tar"
    dest: "/home/vagrant/"
    copy: no

- name: Build ruby.
  command: >
    {{ item }}
    chdir=/home/vagrant/ruby-{{ ruby.version }}
    creates=/usr/local/bin/ruby
  with_items:
    - ./configure --enable-shared
    - make
    - sudo make install

- name: Add ruby symlinks.
  file:
    src: "/usr/local/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
  with_items:
    - erb
    - gem
    - irb
    - rake
    - rdoc
    - ruby
