---
  - name: Install mysql-server
    apt: pkg={{ item }} state=present
    sudo: yes
    with_items:
      - mysql-server
      - mysql-client
      - libmysqlclient-dev
      - python-mysqldb

  - name: Start Mysql Service
    service: name=mysql state=restarted enabled=true
    sudo: yes

  - name: Create databases
    mysql_db: name={{ item.name }} state=present
    with_items: mysql.databases
    when: mysql is defined and mysql.databases is defined

  - name: Create MySQL users
    mysql_user: >
      name={{ item.name }}
      host={{ item.host|default('localhost') }}
      password={{ item.password|default(item.name)}}
      priv={{ item.priv|default('*.*:ALL') }}
      state=present
    with_items: mysql.users
    when: mysql is defined and mysql.users is defined

  - name: Configure mysql server
    template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
    notify:
      - Restart MySQL Server
