---

- name: Install mysql
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
    - python-mysqldb

- name: Start mysql service
  service: name=mysql state=started

- name: Create mysql databases
  mysql_db: name={{ item.name }} state=present
  with_items: mysql.databases|default([])

- name: Create mysql users
  mysql_user: >
    name={{ item.name }}
    password={{ item.password|default(item.name)}}
    host={{ item.host|default('%')}}
    priv={{ item.priv|default('*.*:ALL') }}
    state=present
  with_items: mysql.users|default([])

- name: Configure mysql server
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify:
    - Restart mysql
