---

- name: Install/update composer
  shell: >
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer self-update

- name: Make sure main user has .composer directory
  file: dest='{{ main_user_home_dir }}/.composer' state=directory owner={{ main_user }} group={{ main_group }}

- name: Set github personal token for main user
  template: src=auth.json.j2 dest='{{ main_user_home_dir }}/.composer/auth.json' owner={{ main_user }} group={{ main_group }}
  when: composer_github_token != ''
