---

- name: Include php.yml
  include: php.yml

- name: Include apache.yml
  include: apache.yml
  when: apache_mod_php is defined and apache_mod_php

- name: Include fpm.yml
  include: fpm.yml
  when: fpm is defined and fpm
