---

- include: php{{ php_version.split('.')[0] }}.yml

- name: Register php extensions directory
  shell: php -i 2>/dev/null | grep "^extension_dir" | awk -F" => " '{ print $2; }'
  register: php_extension_dir

- include: php{{ php_version.split('.')[0] }}-extensions.yml

- name: Stop apache server in favour of nginx if it was installed unintentionally
  service: name=apache2 state=stopped
  ignore_errors: yes
  notify:
    - Restart nginx
  when: (apache is not defined or not apache) and (nginx is defined and nginx)

- include: apache.yml
  when: apache_mod_php is defined and apache_mod_php

- include: fpm.yml
  when: fpm is defined and fpm
