---

- name: Install php5.6
  apt: name={{ item }} state=present
  with_items:
    - php5.6
    - php5.6-cli
    - php5.6-dev
    - php-pear

- name: Configure php5.6 cli
  template: src=php.ini.j2 dest="/etc/php/5.6/cli/php.ini" mode=0644
