---

- name: Install php5 fpm lib
  apt: name={{ item }} state=present
  with_items:
    - php5-fpm

- name: Configure php5 fpm
  template: src=php.ini.j2 dest="/etc/php5/fpm/php.ini" mode=0644

- name: Configure php5 fpm pools
  template: src=php-fpm.pool.conf.j2 dest="/etc/php5/fpm/pool.d/{{ item.name }}.conf" mode=0644
  with_items: fpm_pools
  notify:
    - Restart php5-fpm

- name: Configure php5 xdebug fpm
  template: src=xdebug.ini.j2 dest="/etc/php5/fpm/conf.d/20-xdebug.ini" mode=0644
  notify:
    - Restart php5-fpm
  when: ('php5-xdebug' in php5_extensions)

- name: Configure php5 redis fpm for ubuntu < 14.04
  file: src=/etc/php5/mods-available/redis.ini dest=/etc/php5/fpm/conf.d/30-redis.ini state=link
  notify:
    - Restart php5-fpm
  when: ('php5-redis' in php5_extensions) and (ansible_distribution_version|version_compare('14.04', '<'))

- name: Configure php5 stomp
  file: src=/etc/php5/mods-available/stomp.ini dest=/etc/php5/fpm/conf.d/30-stomp.ini state=link
  notify:
    - Restart php5-fpm
  when: ('php5-stomp' in php5_extensions)
