---

- name: Install php5.6 apache lib
  apt: name={{ item }} state=present
  with_items:
    - libapache2-mod-php5.6

- name: Configure php5.6 apache
  template: src=php.ini.j2 dest=/etc/php/5.6/apache2/php.ini owner=root group=root mode=0644

- name: Disable apache mod-php5.6
  shell: a2dismod php5.6
