---

- name: Register php extensions directory
  shell: php -i 2>/dev/null | grep extension_dir | awk -F" => " '{ print $2; }'
  register: php_extension_dir

- name: Add ppa mongodb-drivers for ubuntu < 14.04
  apt_repository: repo="ppa:chris-lea/mongodb-drivers" state=present
  when: ('php5-mongo' in php5_extensions) and (ansible_distribution_version|version_compare('14.04', '<'))

- name: Install php5 extensions for ubuntu < 14.04
  apt: name={{ item }} state=present
  with_items: php5_extensions|difference(['php5-redis', 'php5-stomp', 'php5-amqp'])
  when: ansible_distribution_version|version_compare('14.04', '<')

- name: Install php5 extensions for ubuntu >= 14.04
  apt: name={{ item }} state=present
  with_items: php5_extensions|difference(['php5-stomp', 'php5-amqp'])
  when: ansible_distribution_version|version_compare('14.04', '>=')

- name: Configure php5 cli xdebug
  template: src=xdebug.ini.j2 dest="/etc/php5/cli/conf.d/20-xdebug.ini" mode=0644
  when: ('php5-xdebug' in php5_extensions)

- name: Disable php5 cli xdebug (if wanted)
  file: dest="/etc/php5/cli/conf.d/20-xdebug.ini" state=absent
  when: (php_disable_xdebug_cli is defined and php_disable_xdebug_cli)

- name: Install php5 redis for ubuntu < 14.04
  shell: >
    test -f /etc/php5/mods-available/redis.ini || \
    (pecl install redis && touch /etc/php5/mods-available/redis.ini && echo "extension=redis.so" > /etc/php5/mods-available/redis.ini)
  when: ('php5-redis' in php5_extensions) and (ansible_distribution_version|version_compare('14.04', '<'))

- name: Configure php5 redis cli for ubuntu < 14.04
  file: src=/etc/php5/mods-available/redis.ini dest=/etc/php5/cli/conf.d/30-redis.ini state=link
  when: ('php5-redis' in php5_extensions) and (ansible_distribution_version|version_compare('14.04', '<'))

- name: Install php5 stomp
  shell: >
    test -f /etc/php5/mods-available/stomp.ini || \
    (yes "no" | pecl install stomp && touch /etc/php5/mods-available/stomp.ini && echo "extension=stomp.so" > /etc/php5/mods-available/stomp.ini)
  when: ('php5-stomp' in php5_extensions)

- name: Configure php5 stomp cli
  file: src=/etc/php5/mods-available/stomp.ini dest=/etc/php5/cli/conf.d/30-stomp.ini state=link
  when: ('php5-stomp' in php5_extensions)

- name: Install php5 librabbitmq-dev for php5-amqp extension
  apt: name=librabbitmq-dev state=present
  when: ('php5-amqp' in php5_extensions)

- name: Install php5 amqp-1.4.0
  shell: >
    test -f /etc/php5/mods-available/amqp.ini || \
    (yes "no" | pecl install amqp-1.4.0 && touch /etc/php5/mods-available/amqp.ini && echo "extension=amqp.so" > /etc/php5/mods-available/amqp.ini)
  when: ('php5-amqp' in php5_extensions)

- name: Configure php5 amqp cli
  file: src=/etc/php5/mods-available/amqp.ini dest=/etc/php5/cli/conf.d/30-amqp.ini state=link
  when: ('php5-amqp' in php5_extensions)
