---

- name: Register php5.6 extensions directory
  shell: php5.6 -i 2>/dev/null | grep "^extension_dir" | awk -F" => " '{ print $2; }'
  register: php_extension_dir

- name: Install php5.6 extensions
  apt: name={{ item }} state=present
  with_items: php56_extensions

- name: Configure php5.6 cli xdebug
  template: src=xdebug.ini.j2 dest="/etc/php/5.6/cli/conf.d/20-xdebug.ini" mode=0644
  when: ('php-xdebug' in php56_extensions)

- name: Disable php5.6 cli xdebug (if wanted)
  file: dest="/etc/php/5.6/cli/conf.d/20-xdebug.ini" state=absent
  when: (php_disable_xdebug_cli is defined and php_disable_xdebug_cli)
