---

- name: Install php7.0
  apt: name={{ item }} state=present
  with_items:
    - php7.0
    - php7.0-cli
    - php7.0-dev
    - php-pear

- name: Configure php7.0 cli
  template: src=php.ini.j2 dest="/etc/php/7.0/cli/php.ini" mode=0644
