---

- name: Register php7.0 extensions directory
  shell: php7.0 -i 2>/dev/null | grep "^extension_dir" | awk -F" => " '{ print $2; }'
  register: php_extension_dir

- name: Install php7.0 extensions
  apt: name={{ item }} state=present
  with_items: php70_extensions

- name: Configure php7.0 cli xdebug
  template: src=xdebug.ini.j2 dest="/etc/php/7.0/cli/conf.d/20-xdebug.ini" mode=0644
  when: ('php-xdebug' in php70_extensions)

- name: Disable php7.0 cli xdebug (if wanted)
  file: dest="/etc/php/7.0/cli/conf.d/20-xdebug.ini" state=absent
  when: (php_disable_xdebug_cli is defined and php_disable_xdebug_cli)
