---

- name: Install php7.1 extensions
  apt: name={{ item }} state=present
  with_items: '{{ php71_extensions }}'

- name: Configure php7.1 xdebug
  template: src=xdebug.ini.j2 dest="/etc/php/7.1/mods-available/xdebug.ini" mode=0644
  when: ('php-xdebug' in php71_extensions)

- name: Disable xdebug for php7.1 phpdbg
  file: dest="/etc/php/7.1/phpdbg/conf.d/20-xdebug.ini" state=absent
  when: ('php7.1-phpdbg' in php71_extensions)

- name: Disable xdebug for php7.1 cli
  file: dest="/etc/php/7.1/cli/conf.d/20-xdebug.ini" state=absent
  when: (php_disable_xdebug_cli is defined and php_disable_xdebug_cli)
