---

- name: Check if elasticsearch-HQ is already installed
  stat: path=/usr/share/elasticsearch/plugins/HQ
  register: es_HQ

- name: Install elasticsearch-HQ plugin
  command: /usr/share/elasticsearch/bin/plugin install royrusso/elasticsearch-HQ/{{ elasticsearch_hq_branch }}
  notify:
    - Restart elasticsearch
  when: not es_HQ.stat.exists
