---

- name: Create /etc/apollo directory
  file: dest='/etc/apollo' state=directory

- name: Download apollo archive
  get_url:
    url: 'http://apache.crihan.fr/dist/activemq/activemq-apollo/{{ apollo_version }}/apache-apollo-{{ apollo_version }}-unix-distro.tar.gz'
    dest: '/tmp/apollo-{{ apollo_version }}.tar.gz'

- name: Extract apollo archive in /etc/apollo
  command: 'tar zxf /tmp/apollo-{{ apollo_version }}.tar.gz -C /etc/apollo --strip-components=1'

- name: Create apollo broker instance
  shell: >
    cd /var/lib
    && /etc/apollo/bin/apollo create apollobroker
    && ln -s /var/lib/apollobroker/bin/apollo-broker-service /etc/init.d/

- name: Configure apollo broker
  template: src=apollo.xml.j2 dest=/var/lib/apollobroker/etc/apollo.xml
  notify:
    - Restart apollo-broker-service

- name: Start apollo-broker-service
  service: name=apollo-broker-service state=started
