---

- name: Install wkhtmltopdf dependencies
  apt: name={{ item }} state=present
  with_items:
    - libxrender1
    - x11-common
    - fontconfig
    - libfontenc1
    - libxfont1
    - xfonts-75dpi
    - xfonts-base
    - xfonts-encodings
    - xfonts-utils
    - libjpeg-turbo8

- name: Create wkhtmltopdf app directory
  file: state=directory path=/opt/wkhtmltopdf

- name: Download wkhtmltopdf
  get_url:
    url: 'http://download.gna.org/wkhtmltopdf/{{ wkhtmltopdf_version }}/{{ wkhtmltopdf_version_full }}/wkhtmltox-{{ wkhtmltopdf_version_full }}_linux-{{ ansible_lsb.codename }}-amd64.deb'
    dest: '/opt/wkhtmltopdf/wkhtmltox-{{ wkhtmltopdf_version_full }}_linux-{{ ansible_lsb.codename }}-amd64.deb'

- name: Install wkthtmltopdf
  apt: deb='/opt/wkhtmltopdf/wkhtmltox-{{ wkhtmltopdf_version_full }}_linux-{{ ansible_lsb.codename }}-amd64.deb' state=present

- name: Add wkthtmltopdf symlink
  file:
    src: /usr/local/bin/wkhtmltopdf
    dest: /usr/bin/wkhtmltopdf
    state: link
