---

- name: Install oh-my-zsh
  shell: >
    wget -qO - https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash - && \
    cp -R ~/.oh-my-zsh '{{ main_user_home_dir }}/'

- name: Configure oh-my-zsh for root user
  template: src=zshrc.j2 dest=~/.zshrc

- name: Configure oh-my-zsh for main user
  template: src=zshrc.j2 dest='{{ main_user_home_dir }}/.zshrc'

- name: Set zsh as default shell for root user
  user: name=root shell=/bin/zsh

- name: Set zsh as default shell for main user
  user: name={{ main_user }} shell=/bin/zsh
