---

- name: Add kibana gpg key
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

- name: Add kibana repo
  apt_repository: repo='deb https://artifacts.elastic.co/packages/{{ kibana_version }}/apt stable main' state=present

- name: Install kibana
  apt: name=kibana state=present

- name: Make kibana start automatically when the system boots up
  shell: update-rc.d kibana defaults 95 10

- name: Start kibana
  service: name=kibana state=started
