---

- name: Add logstash gpg key
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

- name: Add logstash repo
  apt_repository: repo='deb https://artifacts.elastic.co/packages/{{ logstash_version }}/apt stable main' state=present

- name: Install logstash in /opt/logstash/bin
  apt: name=logstash state=present

- name: Configure logstash
  template: src=logstash.conf.j2 dest=/etc/logstash/conf.d/logstash.conf
  notify:
    - Restart logstash

- name: Start logstash
  service: name=logstash state=started
