---

- name: Add logstash gpg key
  shell: wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | apt-key add -

- name: Add logstash repo
  shell: echo 'deb http://packages.elastic.co/logstash/{{ logstash_version }}/debian stable main' > /etc/apt/sources.list.d/logstash.list

- name: Install logstash in /opt/logstash/bin
  apt: name=logstash state=present update_cache=yes

- name: Configure logstash
  template: src=logstash.conf.j2 dest=/etc/logstash/conf.d/logstash.conf
  notify:
    - Restart logstash

- name: Start logstash
  service: name=logstash state=started
