---

- name: Download logstash < 5.0
  get_url:
    url: 'https://download.elastic.co/logstash/logstash/packages/debian/logstash-{{ logstash_version }}_all.deb'
    dest: '/tmp/logstash-{{ logstash_version }}.deb'
  when: logstash_version|match('^[0-2]')

- name: Download logstash >= 5.0
  get_url:
    url: 'https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}.deb'
    dest: '/tmp/logstash-{{ logstash_version }}.deb'
  when: not (logstash_version|match('^[0-2]'))

- name: Install logstash
  apt: deb='/tmp/logstash-{{ logstash_version }}.deb' state=present

- name: Configure logstash
  template: src=logstash.conf.j2 dest=/etc/logstash/conf.d/logstash.conf
  notify:
    - Restart logstash

- name: Start logstash
  service: name=logstash state=started
